### ISSUE TITLE
I am trying to migrate this library i am getting this error

### ISSUE THREAD

**Issue by tahercoolguy** [jonathanrickard/django-simple-bulk-emailer#1]
must inherit from SortableAdminBase since EmailDocumentInline inherits from SortableInlineAdminMixin.

**Comment by jonathanrickard** [comment]
Hi. I am unable to reproduce the error with a fresh or upgraded installation. Please review the six steps of installation, and then provide additional information about your configuration to assist in troubleshooting.

**Comment by tahercoolguy** [comment]
thanks issue resolved
